[project]
name = "kmux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiorwlock>=1.5.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
    "psutil>=7.0.0",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "ipython>=9.5.0",
]
